<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_Bills</name>
   <tag></tag>
   <elementGuidId>f9e4585f-8815-4b4b-9d0d-dd244ab3f58f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section/ul/li/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.list-1-1-80.is-titlePresent > li > button[type=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-monitoring-label</name>
      <type>Main</type>
      <value>Bill Payment Form Account Card</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bills $420.00 Avl.02-0000-0000000-005</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js csstransforms3d csstransitions&quot;]/body[@class=&quot;t-main-background bodyPaymentModalOpen-1-1-23&quot;]/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;ReactModal__Overlay ReactModal__Overlay--after-open overlay-1-1-25&quot;]/div[@class=&quot;ReactModal__Content ReactModal__Content--after-open modal-1-1-24&quot;]/div[@class=&quot;chooserContainer-1-1-26&quot;]/div[@class=&quot;Container-component-180 scrollContainer-1-1-76&quot;]/div[@class=&quot;body-1-1-77&quot;]/section[1]/ul[@class=&quot;list-1-1-80 is-titlePresent&quot;]/li[1]/button[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Someone new'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li/button</value>
   </webElementXpaths>
</WebElementEntity>
